version: '3.7'
name: 'postgresql-project'
services:
    postgres:
        image: postgres:latest
        restart: always
        environment:
          - POSTGRES_USER=postgres
          - POSTGRES_PASSWORD=postgrespw
        logging:
          options:
            max-size: 10m
            max-file: "3"
        ports:
          - '55001:5432'
        volumes:
          - ./postgres-data:/var/lib/postgresql/data
          # copy the sql script to create tables
          - ./sql/create-schema.sql:/docker-entrypoint-initdb.d/create-schema.sql
          # copy the sql script to fill tables
          - ./sql/populate-data.sql:/docker-entrypoint-initdb.d/populate-data.sql